spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tigeryj/spring-cloud-config
          username: tigeryj
          password: yuejietai163
          search-paths: SC-BOOK-CONFIG

server:
  port: 9090
